openapi: 3.0.4
info:
  title: Pulse Api AllDevices TimeLineEvent API
  description: "# Introduction\n\nThe Pulse API is an HTTP API that is designed to interact with your pulse account and devices. \n\nNote that not all app functionality has yet been exposed through this api, so if you need additional functionality, contact our support team at support@pulsegrow.com and we will add it for you. \n\nThis API reference includes all technical documentation developers need to integrate third-party applications and platforms. If you have any additional questions send an email to our support team at support@pulsegrow.com\n\n# Authentication\n\nAll HTTP requests made against the Pulse API must be validated with an API Key.\n\n### Acquiring an API Key\n\nTo generate a new api key go to https://app.pulsegrow.com/account, scroll down to the api key section, and press the \"Add Api Key\" button.\n\n### Using Your API Key \n\nNote: API keys are generated per grow and only have access to that grow's resources (users, devices, etc). \n\nAll requests should target domain `https://api.pulsegrow.com`.\n\nYou need to provide the API key via the `x-api-key` header.\n\nSecurity Warning: It's important to secure your API Key against public access. Guard and secure it like a password. If you suspect that your API key has been compromised, revoke it via the web application at https://app.pulsegrow.com/account. \n\nSample request:\n\n```\n\ncurl --request GET \"https://api.pulsegrow.com/devices/{deviceId}/recent-data\" --header \"x-api-key: {apiKey}\"\n\n``` \n\n### Api consumption\n\n Api consumption is measured by number of datapoints retrieved.\n\n An api call that does not retrieve datapoints counts as one datapoint.\n\n Hobbyist users can use up to 4800 datapoints daily, Enthusiasts and Professionals 24000 and 120000, respectively \n\n"
  termsOfService: https://pulsegrow.com/terms
  contact:
    name: Need help? Contact support
    email: support@pulsegrow.com
  version: v1
  x-logo:
    url: https://cdn.shopify.com/s/files/1/2451/2393/files/logo_1_400x.png
    altText: The Logo
tags:
- name: TimeLineEvent
  description: A collection of API operations related to timeline events.
paths:
  /api/timeline:
    get:
      tags:
      - TimeLineEvent
      summary: "Retrieves timeline events for grow. \nSupports pagination by page and number of retrieved events.\nSupports filtering by range and event types."
      parameters:
      - name: eventTypes
        in: query
        description: Types of events to include
        schema:
          type: array
          items:
            $ref: '#/components/schemas/TimelineEventType'
      - name: startDate
        in: query
        description: Starting day of event selection. 30 days prior will be used as starting date if not provided
        schema:
          type: string
          format: date-time
      - name: endDate
        in: query
        description: Last day day of event selection. 30 days after today will be used as starting date if not provided
        schema:
          type: string
          format: date-time
      - name: count
        in: query
        description: Number of events to include
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        description: pagination
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimelineEventDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    TimelineEventDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
          nullable: true
        createdAt:
          type: string
          format: date-time
          nullable: true
        updatedAt:
          type: string
          format: date-time
          nullable: true
        timelineEventType:
          $ref: '#/components/schemas/TimelineEventType'
        title:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
        display:
          type: boolean
        growId:
          type: integer
          format: int32
          nullable: true
      additionalProperties: false
    TimelineEventType:
      type: integer
      format: int32
