openapi: 3.2.0
info:
  title: Pulse Time Line Event API
  description: '# Introduction


    The Pulse API is an HTTP API that is designed to interact with your pulse account and devices.'
  termsOfService: https://pulsegrow.com/terms
  contact:
    name: Need help? Contact support
    email: support@pulsegrow.com
  version: v1
  x-logo:
    url: https://cdn.shopify.com/s/files/1/2451/2393/files/logo_1_400x.png
    altText: The Logo
tags:
- name: TimeLineEvent
  description: A collection of API operations related to timeline events.
paths:
  /api/timeline:
    get:
      tags:
      - TimeLineEvent
      summary: Retrieves timeline events for grow.
      parameters:
      - name: eventTypes
        in: query
        description: Types of events to include
        schema:
          type: array
          items:
            $ref: '#/components/schemas/TimelineEventType'
      - name: startDate
        in: query
        description: Starting day of event selection. 30 days prior will be used as starting date if not provided
        schema:
          type: string
          format: date-time
      - name: endDate
        in: query
        description: Last day day of event selection. 30 days after today will be used as starting date if not provided
        schema:
          type: string
          format: date-time
      - name: count
        in: query
        description: Number of events to include
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        description: pagination
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimelineEventDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      operationId: getApiTimeline
      x-operation-id-source: derived
components:
  schemas:
    TimelineEventType:
      type: integer
      format: int32
    TimelineEventDto:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        createdAt:
          type:
          - string
          - 'null'
          format: date-time
        updatedAt:
          type:
          - string
          - 'null'
          format: date-time
        timelineEventType:
          $ref: '#/components/schemas/TimelineEventType'
        title:
          type:
          - string
          - 'null'
        detail:
          type:
          - string
          - 'null'
        display:
          type: boolean
        growId:
          type:
          - integer
          - 'null'
          format: int32
      additionalProperties: false
