openapi: 3.2.0
info:
  title: Pulse Pro Light Reading API
  description: '# Introduction


    The Pulse API is an HTTP API that is designed to interact with your pulse account and devices.'
  termsOfService: https://pulsegrow.com/terms
  contact:
    name: Need help? Contact support
    email: support@pulsegrow.com
  version: v1
  x-logo:
    url: https://cdn.shopify.com/s/files/1/2451/2393/files/logo_1_400x.png
    altText: The Logo
tags:
- name: ProLightReading
  description: A collection of API operations related to light readings.
paths:
  /api/light-readings/{deviceId}:
    get:
      tags:
      - ProLightReading
      summary: Retrieves (one page worth of) light readings(including spectrum) for a given…
      parameters:
      - name: deviceId
        in: path
        description: Id of the device
        required: true
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        description: Object containing requested page position. Note that page numeration starts from zero
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LightReadingsResponseDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      operationId: getApiLightReadingsByDeviceId
      x-operation-id-source: derived
  /api/devices/{deviceId}/trigger-light-reading:
    get:
      tags:
      - ProLightReading
      summary: Remotely triggers a light reading off of a Pulse Pro.
      parameters:
      - name: deviceId
        in: path
        description: Id of the device
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IActionResult'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      operationId: getApiDevicesByDeviceIdTriggerLightReading
      x-operation-id-source: derived
components:
  schemas:
    ProLightReadingDto:
      type: object
      properties:
        deviceId:
          type: integer
          format: int32
        id:
          type: integer
          format: int32
        createdAt:
          type: string
          format: date-time
        note:
          type:
          - string
          - 'null'
        channel1:
          type: number
          format: double
        channel2:
          type: number
          format: double
        channel3:
          type: number
          format: double
        channel4:
          type: number
          format: double
        channel5:
          type: number
          format: double
        channel6:
          type: number
          format: double
        channel7:
          type: number
          format: double
        channel8:
          type: number
          format: double
        ir:
          type: number
          format: double
        clear:
          type: number
          format: double
        flicker:
          type: number
          format: double
        gain:
          type: integer
          format: int32
        tint:
          type: number
          format: double
        ppfd:
          type: number
          format: double
        dli:
          type:
          - number
          - 'null'
          format: double
        pfdRed:
          type:
          - number
          - 'null'
          format: double
        pfdGreen:
          type:
          - number
          - 'null'
          format: double
        pfdBlue:
          type:
          - number
          - 'null'
          format: double
        pfdIr:
          type:
          - number
          - 'null'
          format: double
        spectrum:
          type:
          - array
          - 'null'
          items:
            type: number
            format: double
      additionalProperties: false
    LightReadingsResponseDto:
      type: object
      properties:
        currentPage:
          type: integer
          format: int32
        numPages:
          type: integer
          format: int32
        numReadings:
          type: integer
          format: int32
        lightReadings:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ProLightReadingDto'
      additionalProperties: false
    IActionResult:
      type: object
      additionalProperties: false
