openapi: 3.2.0
info:
  title: Pulse Invitation API
  description: '# Introduction


    The Pulse API is an HTTP API that is designed to interact with your pulse account and devices.'
  termsOfService: https://pulsegrow.com/terms
  contact:
    name: Need help? Contact support
    email: support@pulsegrow.com
  version: v1
  x-logo:
    url: https://cdn.shopify.com/s/files/1/2451/2393/files/logo_1_400x.png
    altText: The Logo
tags:
- name: Invitation
  description: A collection of API operations related to inviting users.
paths:
  /invitations:
    get:
      tags:
      - Invitation
      summary: List of invitations that have been sent, but not yet been accepted or canceled
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ViewInvitationDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      operationId: getInvitations
      x-operation-id-source: derived
components:
  schemas:
    UserGrowRole:
      type: integer
      format: int32
    ViewInvitationDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        growId:
          type: integer
          format: int32
        sendingUserId:
          type: integer
          format: int32
        sendingUserEmail:
          type:
          - string
          - 'null'
        statusId:
          type: integer
          format: int32
        invitedUserId:
          type:
          - integer
          - 'null'
          format: int32
        invitedUserEmail:
          type:
          - string
          - 'null'
        role:
          $ref: '#/components/schemas/UserGrowRole'
        dateSent:
          type: string
          format: date-time
        dateAccepted:
          type:
          - string
          - 'null'
          format: date-time
        dateDeclined:
          type:
          - string
          - 'null'
          format: date-time
        dateCancelled:
          type:
          - string
          - 'null'
          format: date-time
      additionalProperties: false
