openapi: 3.2.0
info:
  title: Pulse Hub API
  description: '# Introduction


    The Pulse API is an HTTP API that is designed to interact with your pulse account and devices.'
  termsOfService: https://pulsegrow.com/terms
  contact:
    name: Need help? Contact support
    email: support@pulsegrow.com
  version: v1
  x-logo:
    url: https://cdn.shopify.com/s/files/1/2451/2393/files/logo_1_400x.png
    altText: The Logo
tags:
- name: Hub
  description: A collection of API operations related to users.
paths:
  /hubs/ids:
    get:
      tags:
      - Hub
      summary: All Hub Ids
      description: Retrieves all of the hubs ids assigned to the grow.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                  format: int32
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      operationId: getHubsIds
      x-operation-id-source: derived
  /hubs/{hubId}:
    get:
      tags:
      - Hub
      summary: Gets details for hub
      parameters:
      - name: hubId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HubDetailsDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      operationId: getHubsByHubId
      x-operation-id-source: derived
components:
  schemas:
    DeviceType:
      type: integer
      format: int32
    SensorType:
      type: integer
      format: int32
    HubThresholdDto:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        notificationActive:
          type:
          - boolean
          - 'null'
        lowThresholdValue:
          type:
          - number
          - 'null'
          format: double
        highThresholdValue:
          type:
          - number
          - 'null'
          format: double
        delay:
          type:
          - string
          - 'null'
          format: date-span
        day:
          type:
          - boolean
          - 'null'
        hubId:
          type:
          - integer
          - 'null'
          format: int32
        thresholdType:
          $ref: '#/components/schemas/HubThresholdType'
      additionalProperties: false
    HubDetailsDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type:
          - string
          - 'null'
        hubThresholds:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/HubThresholdDto'
        hidden:
          type: boolean
        macAddress:
          type:
          - string
          - 'null'
        growId:
          type: integer
          format: int32
        sensorDevices:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/SensorDeviceViewDto'
      additionalProperties: false
    HubThresholdType:
      type: integer
      format: int32
    ParSensorSubtype:
      type: integer
      format: int32
    SensorDeviceViewDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        displayOrder:
          type:
          - integer
          - 'null'
          format: int32
        name:
          type:
          - string
          - 'null'
        growId:
          type: integer
          format: int32
        hidden:
          type: boolean
        hubId:
          type:
          - integer
          - 'null'
          format: int32
        parSensorSubtype:
          $ref: '#/components/schemas/ParSensorSubtype'
        deviceType:
          $ref: '#/components/schemas/DeviceType'
        sensorType:
          $ref: '#/components/schemas/SensorType'
      additionalProperties: false
