openapi: 3.2.0
info:
  title: Pulse All Devices API
  description: '# Introduction


    The Pulse API is an HTTP API that is designed to interact with your pulse account and devices.'
  termsOfService: https://pulsegrow.com/terms
  contact:
    name: Need help? Contact support
    email: support@pulsegrow.com
  version: v1
  x-logo:
    url: https://cdn.shopify.com/s/files/1/2451/2393/files/logo_1_400x.png
    altText: The Logo
tags:
- name: AllDevices
  description: A collection of API operations related to devices.
paths:
  /all-devices:
    get:
      tags:
      - AllDevices
      summary: Gets all of the grows devices, including latest data.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NonTypeSpecificDeviceListDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      operationId: getAllDevices
      x-operation-id-source: derived
components:
  schemas:
    SensorDeviceViewUniversalDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        displayOrder:
          type:
          - integer
          - 'null'
          format: int32
        name:
          type:
          - string
          - 'null'
        growId:
          type: integer
          format: int32
        hidden:
          type: boolean
        hubId:
          type:
          - integer
          - 'null'
          format: int32
        deviceType:
          $ref: '#/components/schemas/DeviceType'
        mostRecentDataPoint:
          $ref: '#/components/schemas/UniversalDataPointDto'
        sensorType:
          $ref: '#/components/schemas/SensorType'
        lastHourDataPointDtos:
          $ref: '#/components/schemas/UniversalDataPointArrayDto'
        templateId:
          type:
          - integer
          - 'null'
          format: int32
        dayStart:
          type: string
          format: date-span
        nightStart:
          type: string
          format: date-span
        parSensorSubtype:
          $ref: '#/components/schemas/ParSensorSubtype'
      additionalProperties: false
    SensorReadingType:
      type: integer
      format: int32
    UniversalDataPointDtoMultipleValue:
      type: object
      properties:
        paramName:
          type:
          - string
          - 'null'
        measuringUnit:
          type:
          - string
          - 'null'
        paramValues:
          type:
          - array
          - 'null'
          items:
            type: number
            format: float
        highChartAuxiliaryData:
          $ref: '#/components/schemas/HighChartAuxiliaryData'
        sensorReadingType:
          $ref: '#/components/schemas/SensorReadingType'
      additionalProperties: false
    DataPointDto:
      type: object
      properties:
        deviceId:
          type: integer
          format: int32
        pluggedIn:
          type: boolean
        batteryV:
          type: number
          format: float
        electricImpId:
          type:
          - string
          - 'null'
        signalStrength:
          type: integer
          format: int32
        createdAt:
          type: string
          format: date-time
        deviceType:
          $ref: '#/components/schemas/DeviceType'
        temperatureF:
          type: number
          format: float
        humidityRh:
          type: number
          format: float
        lightLux:
          type: number
          format: float
        airPressure:
          type: number
          format: float
        vpd:
          type: number
          format: double
        co2:
          type: integer
          format: int32
        co2Temperature:
          type: number
          format: double
        co2Rh:
          type: number
          format: double
        voc:
          type: integer
          format: int32
        channel1:
          type: number
          format: double
        channel2:
          type: number
          format: double
        channel3:
          type: number
          format: double
        channel4:
          type: number
          format: double
        channel5:
          type: number
          format: double
        channel6:
          type: number
          format: double
        channel7:
          type: number
          format: double
        channel8:
          type: number
          format: double
        near:
          type: number
          format: double
        clear:
          type: number
          format: double
        flicker:
          type: number
          format: double
        par:
          type: number
          format: double
        gain:
          type: integer
          format: int32
        tint:
          type: number
          format: double
      additionalProperties: false
    NextOpenSprinklerProgramRunInfo:
      type: object
      properties:
        programId:
          type: integer
          format: int32
        inDays:
          type: integer
          format: int32
        startTime:
          type:
          - string
          - 'null'
          format: date-span
        programName:
          type:
          - string
          - 'null'
        dayOfRun:
          type: string
          format: date-time
      additionalProperties: false
    UniversalDataPointDto:
      type: object
      properties:
        dataPointValues:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/UniversalDataPointDtoSingleValue'
        sensorId:
          type: integer
          format: int32
        createdAt:
          type: string
          format: date-time
      additionalProperties: false
    ParSensorSubtype:
      type: integer
      format: int32
    UniversalDataPointArrayDto:
      type: object
      properties:
        dataPointValues:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/UniversalDataPointDtoMultipleValue'
        dataPointValuesCreatedAt:
          type:
          - array
          - 'null'
          items:
            type: string
            format: date-time
      additionalProperties: false
    SensorType:
      type: integer
      format: int32
    UniversalDataPointDtoSingleValue:
      type: object
      properties:
        paramName:
          type:
          - string
          - 'null'
        measuringUnit:
          type:
          - string
          - 'null'
        paramValue:
          type:
          - number
          - 'null'
          format: float
        highChartAuxiliaryData:
          $ref: '#/components/schemas/HighChartAuxiliaryData'
        sensorReadingType:
          $ref: '#/components/schemas/SensorReadingType'
      additionalProperties: false
    MostRecentSensorDataPointDto:
      type: object
      properties:
        sensorType:
          $ref: '#/components/schemas/SensorType'
        deviceType:
          $ref: '#/components/schemas/DeviceType'
        name:
          type:
          - string
          - 'null'
        dataPointDto:
          $ref: '#/components/schemas/UniversalDataPointDto'
      additionalProperties: false
    DeviceType:
      type: integer
      format: int32
    HubDataPointDto:
      type: object
      properties:
        deviceId:
          type: integer
          format: int32
        pluggedIn:
          type: boolean
        batteryV:
          type: number
          format: float
        electricImpId:
          type:
          - string
          - 'null'
        signalStrength:
          type: integer
          format: int32
        createdAt:
          type: string
          format: date-time
      additionalProperties: false
    HighChartAuxiliaryData:
      type: object
      properties:
        color:
          type:
          - string
          - 'null'
          readOnly: true
        yAxis:
          type: integer
          format: int32
        valueDecimal:
          type: integer
          format: int32
        redCoefficient:
          type: integer
          format: int32
        greenCoefficient:
          type: integer
          format: int32
        blueCoefficient:
          type: integer
          format: int32
      additionalProperties: false
    DeviceViewDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        displayOrder:
          type:
          - integer
          - 'null'
          format: int32
        name:
          type:
          - string
          - 'null'
        growId:
          type: integer
          format: int32
        hidden:
          type: boolean
        deviceType:
          $ref: '#/components/schemas/DeviceType'
        guid:
          type: string
          format: uuid
        templateId:
          type:
          - integer
          - 'null'
          format: int32
        pulseGuid:
          type: string
          format: uuid
        dayStart:
          type: string
          format: date-span
        nightStart:
          type: string
          format: date-span
        isDay:
          type: boolean
        vpdLeafTempOffsetInF:
          type: number
          format: double
        vpdTarget:
          type:
          - number
          - 'null'
          format: double
        batteryCount:
          type: integer
          format: int32
        lowBatteryVoltage:
          type: number
          format: float
        mostRecentDataPoint:
          $ref: '#/components/schemas/DataPointDto'
        lastHourData:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DataPointDto'
        proLightReadingPreviewDto:
          $ref: '#/components/schemas/ProLightReadingPreviewDto'
        growTimezoneOffset:
          type: integer
          format: int32
      additionalProperties: false
    NonTypeSpecificDeviceListDto:
      type: object
      properties:
        deviceViewDtos:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DeviceViewDto'
        universalSensorViews:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/SensorDeviceViewUniversalDto'
        hubViewDtos:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/HubViewDto'
        controlsViewDtos:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ControlsViewDto'
      additionalProperties: false
    LastAutomationInfo:
      type: object
      properties:
        durations:
          type:
          - array
          - 'null'
          items:
            type: integer
            format: int32
        sensorId:
          type: integer
          format: int32
        triggeringValue:
          type:
          - string
          - 'null'
        time:
          type: string
          format: date-time
        mostRecentSensorDataPointDto:
          $ref: '#/components/schemas/MostRecentSensorDataPointDto'
      additionalProperties: false
    OpenSprinklerSpecificData:
      type: object
      properties:
        lastOnline:
          type:
          - string
          - 'null'
          format: date-time
        nextOpenSprinklerProgramRunInfo:
          $ref: '#/components/schemas/NextOpenSprinklerProgramRunInfo'
        lastRanProgramName:
          type:
          - string
          - 'null'
        lastRunProgramId:
          type:
          - integer
          - 'null'
          format: int32
        mac:
          type:
          - string
          - 'null'
        lastRunDuration:
          type:
          - integer
          - 'null'
          format: int32
        lastRunTimeEnd:
          type:
          - string
          - 'null'
          format: date-time
        pausedUntil:
          type:
          - string
          - 'null'
          format: date-time
        lastSynced:
          type:
          - string
          - 'null'
          format: date-time
        durations:
          type:
          - array
          - 'null'
          items:
            type: integer
            format: int32
        lastAutomationInfo:
          $ref: '#/components/schemas/LastAutomationInfo'
      additionalProperties: false
    ControlsViewDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type:
          - string
          - 'null'
        controlType:
          $ref: '#/components/schemas/ControlType'
        displayOrder:
          type:
          - integer
          - 'null'
          format: int32
        deviceType:
          $ref: '#/components/schemas/DeviceType'
        openSprinklerSpecificData:
          $ref: '#/components/schemas/OpenSprinklerSpecificData'
      additionalProperties: false
    ControlType:
      type: integer
      format: int32
    ProLightReadingPreviewDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        ppfd:
          type: number
          format: double
        dli:
          type:
          - number
          - 'null'
          format: double
        createdAt:
          type: string
          format: date-time
      additionalProperties: false
    HubViewDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        displayOrder:
          type:
          - integer
          - 'null'
          format: int32
        name:
          type:
          - string
          - 'null'
        growId:
          type: integer
          format: int32
        hidden:
          type: boolean
        deviceType:
          $ref: '#/components/schemas/DeviceType'
        mostRecentDataPoint:
          $ref: '#/components/schemas/HubDataPointDto'
      additionalProperties: false
