openapi: 3.2.0
info:
  title: Pulse User API
  description: '# Introduction


    The Pulse API is an HTTP API that is designed to interact with your pulse account and devices.'
  termsOfService: https://pulsegrow.com/terms
  contact:
    name: Need help? Contact support
    email: support@pulsegrow.com
  version: v1
  x-logo:
    url: https://cdn.shopify.com/s/files/1/2451/2393/files/logo_1_400x.png
    altText: The Logo
tags:
- name: User
  description: A collection of API operations related to users.
paths:
  /users:
    get:
      tags:
      - User
      summary: List of users and their data for api key
      description: Retrieves all users for the grow that is bound the the api key.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserUsageInformation'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      operationId: getUsers
      x-operation-id-source: derived
components:
  schemas:
    UserUsageInformation:
      type: object
      properties:
        userId:
          type: integer
          format: int32
        userEmail:
          type:
          - string
          - 'null'
        userName:
          type:
          - string
          - 'null'
        lastActive:
          type:
          - string
          - 'null'
          format: date-time
        role:
          type:
          - string
          - 'null'
      additionalProperties: false
